FROM ruby:2.3.1

# Run updates
ARG NPM_CONFIG_LOGLEVEL=info
ARG APP_SERVER_PATH=/srv/www

RUN curl -sL https://deb.nodesource.com/setup_6.x | bash - && \
    apt-get update -qq                                     && \
    apt-get install -y nodejs                              && \
    npm install -g coffeelint                              && \
    mkdir $APP_SERVER_PATH

WORKDIR $APP_SERVER_PATH

# that only invalidates in case of changes in the Gemfile
COPY Gemfile* ${APP_SERVER_PATH}/
RUN bundle install --jobs 8 --retry 5
